services:
  app:
    container_name: gestao_vagas_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gestao_vagas
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gestao_vagas_network
    restart: always

  postgres:
    container_name: gestao_vagas_postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_vagas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d gestao_vagas"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - gestao_vagas_network
    restart: always

  pgadmin:
    container_name: gestao_vagas_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    depends_on:
      - postgres
    networks:
      - gestao_vagas_network
    restart: always

networks:
  gestao_vagas_network:
    driver: bridge

volumes:
  postgres_data: